//====================================================================================================================================================
// Copyright 2024 Lake Orion Robotics FIRST Team 302
//
// Permission is hereby granted, free of charge, to any person obtaining a copy of this software and associated documentation files (the "Software"),
// to deal in the Software without restriction, including without limitation the rights to use, copy, modify, merge, publish, distribute, sublicense,
// and/or sell copies of the Software, and to permit persons to whom the Software is furnished to do so, subject to the following conditions:
//
// The above copyright notice and this permission notice shall be included in all copies or substantial portions of the Software.
//
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
// MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM,
// DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE
// OR OTHER DEALINGS IN THE SOFTWARE.
//====================================================================================================================================================
// This file was automatically generated by the Team 302 code generator version 1.2.3.6
// Generated on Sunday, February 18, 2024 12:44:30 PM

// C++ Includes
#include <string>

// FRC includes

// Team 302 includes
#include "mechanisms/ClimberManager/decoratormods/HoldState.h"
#include "teleopcontrol/TeleopControl.h"
#include "teleopcontrol/TeleopControlFunctions.h"
#include "utils/logging/Logger.h"

// Third Party Includes

using namespace std;
using namespace ClimberManagerStates;

/// @class ExampleForwardState
/// @brief information about the control (open loop, closed loop position, closed loop velocity, etc.) for a mechanism state
HoldState::HoldState(std::string stateName,
					 int stateId,
					 ClimberManagerAllStatesStateGen *generatedState,
					 ClimberManager *mech) : State(stateName, stateId), m_genState(generatedState), m_mechanism(mech)
{
}

void HoldState::Init()
{
	Logger::GetLogger()->LogData(LOGGER_LEVEL::PRINT, string("ArrivedAt"), string("HoldState"), string("init"));

	m_genState->Init();
	m_mechanism->UpdateTarget(RobotElementNames::MOTOR_CONTROLLER_USAGE::CLIMBER_MANAGER_LEFT_CLIMBER, units::length::inch_t(m_mechanism->getleftClimber()->GetCounts()));
	m_mechanism->UpdateTarget(RobotElementNames::MOTOR_CONTROLLER_USAGE::CLIMBER_MANAGER_RIGHT_CLIMBER, units::length::inch_t(m_mechanism->getrightClimber()->GetCounts()));
}

void HoldState::Run()
{
	// Logger::GetLogger()->LogData(LOGGER_LEVEL::PRINT, string("ArrivedAt"), string("HoldState"), string("run"));
	m_genState->Run();
}

void HoldState::Exit()
{
	m_genState->Exit();
}

bool HoldState::AtTarget()
{
	double left = m_mechanism->getleftClimber()->GetCounts();
	double right = m_mechanism->getrightClimber()->GetCounts();
	double target = 14.5;

	return (((abs(left - target)) <= 0.5) &&
			(abs(right - target) <= 0.5));
}

bool HoldState::IsTransitionCondition(bool considerGamepadTransitions)
{
	// To get the current state use m_mechanism->GetCurrentState()
	auto currentstate = m_mechanism->GetCurrentState();
	return ((AtTarget() && (currentstate == m_mechanism->STATE_INITIALIZE)) || (m_mechanism->IsClimbMode() == false && (currentstate != m_mechanism->STATE_INITIALIZE)));
}
