// clang-format off
//====================================================================================================================================================
// Copyright 2023 Lake Orion Robotics FIRST Team 302
//
// Permission is hereby granted, free of charge, to any person obtaining a copy of this software and associated documentation files (the "Software"),
// to deal in the Software without restriction, including without limitation the rights to use, copy, modify, merge, publish, distribute, sublicense,
// and/or sell copies of the Software, and to permit persons to whom the Software is furnished to do so, subject to the following conditions:
//
// The above copyright notice and this permission notice shall be included in all copies or substantial portions of the Software.
//
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
// MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM,
// DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE
// OR OTHER DEALINGS IN THE SOFTWARE.
//====================================================================================================================================================
// This file was automatically generated by the Team 302 code generator version 1.1.0.0
// Generated on Monday, January 22, 2024 6:53:52 PM

// C++ Includes
#include <string>

// FRC includes

// Team 302 includes
#include "State.h"
#include "mechanisms/thing1DriveWheels/generated/thing1DriveWheels_sparkyOn_StateGen.h"
#include "mechanisms/thing1DriveWheels/decoratormods/thing1DriveWheels_sparkyOn_State.h"
#include "teleopcontrol/TeleopControl.h"
#include "teleopcontrol/TeleopControlFunctions.h"

#include <utils/logging/LoggableItemMgr.h>
#include "utils/logging/Logger.h"
#include <utils/logging/LoggerData.h>
#include <utils/logging/LoggerEnums.h>

// Third Party Includes

using namespace std;

/// @class ExampleForwardState
/// @brief information about the control (open loop, closed loop position, closed loop velocity, etc.) for a mechanism state
thing1DriveWheelssparkyOnState::thing1DriveWheelssparkyOnState ( std::string stateName,
        int stateId,
        thing1DriveWheelssparkyOnStateGen *generatedState ) : State ( stateName, stateId ), m_genState ( generatedState )
{
}

void thing1DriveWheelssparkyOnState::Init()
{
	Logger::GetLogger()->LogData ( LOGGER_LEVEL::PRINT, string ( "ArrivedAt" ), string ( "thing1DriveWheelssparkyOnState" ), string ( "init" ) );

	m_genState->Init();
}

void thing1DriveWheelssparkyOnState::Run()
{
	// Logger::GetLogger()->LogData(LOGGER_LEVEL::PRINT, string("ArrivedAt"), string("thing1DriveWheelssparkyOnState"), string("run"));
	// The target can be updated dynamically by calling:
	// 	    m_genState->SetTargetControl ( .... );
	//      m_genState->MECHANISMBaseStateGen::Init();
	// where MECHANISM is the name of the generated mechanism object

	m_genState->Run();
}

void thing1DriveWheelssparkyOnState::Exit()
{
	m_genState->Exit();
}

bool thing1DriveWheelssparkyOnState::AtTarget()
{
	auto attarget = m_genState->AtTarget();
	return attarget;
}

bool thing1DriveWheelssparkyOnState::IsTransitionCondition ( bool considerGamepadTransitions ) const
{
	// To get the current state use m_genState->GetMECHANISM()->GetCurrentState()
	// where MECHANISM is the name of the generated mechanism object
	bool retval = false;
	if( m_genState->Getthing1DriveWheels()->GetCurrentState() == RobotElementNames::THING1DRIVE_WHEELS_STATE_BL)
	{
		retval = ( considerGamepadTransitions && TeleopControl::GetInstance()->IsButtonPressed ( TeleopControlFunctions::SLOW_MODE ) );
	}


	// auto transition = m_genState->IsTransitionCondition(considerGamepadTransitions);
	// return transition;
	return retval;
}
