// clang-format off
//====================================================================================================================================================
// Copyright 2023 Lake Orion Robotics FIRST Team 302
//
// Permission is hereby granted, free of charge, to any person obtaining a copy of this software and associated documentation files (the "Software"),
// to deal in the Software without restriction, including without limitation the rights to use, copy, modify, merge, publish, distribute, sublicense,
// and/or sell copies of the Software, and to permit persons to whom the Software is furnished to do so, subject to the following conditions:
//
// The above copyright notice and this permission notice shall be included in all copies or substantial portions of the Software.
//
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
// MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM,
// DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE
// OR OTHER DEALINGS IN THE SOFTWARE.
//====================================================================================================================================================
// This file was automatically generated by the Team 302 code generator version 1.1.0.0
// Generated on Sunday, January 21, 2024 4:30:42 PM

// C++ Includes
#include <string>
#include <math.h>

// FRC includes

// Team 302 includes
#include "State.h"
#include "mechanisms/thing1DriveWheels/generated/thing1DriveWheels_TalonOn_StateGen.h"
#include "mechanisms/thing1DriveWheels/decoratormods/thing1DriveWheels_TalonOn_State.h"
#include "teleopcontrol/TeleopControl.h"
#include "teleopcontrol/TeleopControlFunctions.h"

#include <utils/logging/LoggableItemMgr.h>
#include "utils/logging/Logger.h"
#include <utils/logging/LoggerData.h>
#include <utils/logging/LoggerEnums.h>

// Third Party Includes

using namespace std;

/// @class ExampleForwardState
/// @brief information about the control (open loop, closed loop position, closed loop velocity, etc.) for a mechanism state
thing1DriveWheelsTalonOnState::thing1DriveWheelsTalonOnState ( std::string stateName,
        int stateId,
        thing1DriveWheelsTalonOnStateGen *generatedState ) : State ( stateName, stateId ), m_genState ( generatedState )
{
}

void thing1DriveWheelsTalonOnState::Init()
{
	Logger::GetLogger()->LogData ( LOGGER_LEVEL::PRINT, string ( "ArrivedAt" ), string ( "thing1DriveWheelsTalonOnState" ), string ( "init" ) );

	m_genState->Init();
}

void thing1DriveWheelsTalonOnState::Run()
{
	// Logger::GetLogger()->LogData(LOGGER_LEVEL::PRINT, string("ArrivedAt"), string("thing1DriveWheelsTalonOnState"), string("run"));
static double speed = 0;
static double dir  = 1;
speed = speed + 0.1 * dir;
if((speed > 4.0) || (speed < -4.0) )
	dir *= -1;

	m_genState->SetTargetControl ( RobotElementNames::MOTOR_CONTROLLER_USAGE::THING1DRIVE_WHEELS_TALONFX_5, * ( m_genState->Getthing1DriveWheels()->talonMotorControlData ), units::angular_velocity::revolutions_per_minute_t ( units::angular_velocity::radians_per_second_t ( speed ) ) );
	m_genState->thing1DriveWheelsBaseStateGen::Init();
	m_genState->Run();
}

void thing1DriveWheelsTalonOnState::Exit()
{
	m_genState->Exit();
}

bool thing1DriveWheelsTalonOnState::AtTarget()
{
	auto attarget = m_genState->AtTarget();
	return attarget;
}

bool thing1DriveWheelsTalonOnState::IsTransitionCondition ( bool considerGamepadTransitions ) const
{
	// To get the current state use m_genState->GetMECHANISM().GetCurrentState()
	// where MECHANISM is the name of the generated mechanism object

	// auto transition = m_genState->IsTransitionCondition(considerGamepadTransitions);
	// return transition;
	return ( considerGamepadTransitions && TeleopControl::GetInstance()->IsButtonPressed ( TeleopControlFunctions::HOLD_POSITION ) );
}
