// clang-format off
//====================================================================================================================================================
// Copyright 2023 Lake Orion Robotics FIRST Team 302
//
// Permission is hereby granted, free of charge, to any person obtaining a copy of this software and associated documentation files (the "Software"),
// to deal in the Software without restriction, including without limitation the rights to use, copy, modify, merge, publish, distribute, sublicense,
// and/or sell copies of the Software, and to permit persons to whom the Software is furnished to do so, subject to the following conditions:
//
// The above copyright notice and this permission notice shall be included in all copies or substantial portions of the Software.
//
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
// MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM,
// DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE
// OR OTHER DEALINGS IN THE SOFTWARE.
//====================================================================================================================================================
// This file was automatically generated by the Team 302 code generator version 1.1.0.0
// Generated on Sunday, January 21, 2024 4:30:42 PM

// C++ Includes
#include <string>

// FRC includes

// Team 302 includes
#include "State.h"
#include "mechanisms/thing1DriveWheels/generated/thing1DriveWheels_state_BR_StateGen.h"
#include "mechanisms/thing1DriveWheels/decoratormods/thing1DriveWheels_state_BR_State.h"
#include "teleopcontrol/TeleopControl.h"
#include "teleopcontrol/TeleopControlFunctions.h"

#include <utils/logging/LoggableItemMgr.h>
#include "utils/logging/Logger.h"
#include <utils/logging/LoggerData.h>
#include <utils/logging/LoggerEnums.h>

// Third Party Includes

using namespace std;

/// @class ExampleForwardState
/// @brief information about the control (open loop, closed loop position, closed loop velocity, etc.) for a mechanism state
thing1DriveWheelsstate_BRState::thing1DriveWheelsstate_BRState ( std::string stateName,
        int stateId,
        thing1DriveWheelsstate_BRStateGen *generatedState ) : State ( stateName, stateId ), m_genState ( generatedState )
{
}

void thing1DriveWheelsstate_BRState::Init()
{
	Logger::GetLogger()->LogData ( LOGGER_LEVEL::PRINT, string ( "ArrivedAt" ), string ( "thing1DriveWheelsstate_BRState" ), string ( "init" ) );

	m_genState->Init();
}

void thing1DriveWheelsstate_BRState::Run()
{
	// Logger::GetLogger()->LogData(LOGGER_LEVEL::PRINT, string("ArrivedAt"), string("thing1DriveWheelsstate_BRState"), string("run"));
	m_genState->Run();
}

void thing1DriveWheelsstate_BRState::Exit()
{
	m_genState->Exit();
}

bool thing1DriveWheelsstate_BRState::AtTarget()
{
	auto attarget = m_genState->AtTarget();
	return attarget;
}

bool thing1DriveWheelsstate_BRState::IsTransitionCondition ( bool considerGamepadTransitions ) const
{
	bool retval = false;
	if( m_genState->Getthing1DriveWheels()->GetCurrentState() == RobotElementNames::THING1DRIVE_WHEELS_TALON_ON)
	{
		retval = ( considerGamepadTransitions && TeleopControl::GetInstance()->IsButtonPressed ( TeleopControlFunctions::SLOW_MODE ) );
	}

	// auto transition = m_genState->IsTransitionCondition(considerGamepadTransitions);
	// return transition;
	return retval || ( considerGamepadTransitions && TeleopControl::GetInstance()->IsButtonPressed ( TeleopControlFunctions::RESET_POSITION ) );
}
